name: Generate number

permissions:
  contents: write

on:
  schedule:
    # Every 15 minutes
    - cron: '*/15 * * * *'

jobs:
  collect-metadata:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          chmod +x ./build.sh
          ./build.sh

      - name: Collect metadata
        run: |
          python .github/workflows/drng-generator/drng-generator.py >> .github/workflows/drng-generator/raw.txt

      - name: Commit metadata
        run: |
          git config --global user.name 'Dwij Bavisi'
          git config --global user.email 'dwij@dbavisi.net'
          git add .github/workflows/drng-generator/raw.txt
          git commit -m "[Auto] Generate number as of $(date +'%Y-%m-%d %H:%M:%S %z')"
          git push
